### ISSUE TITLE
Invalid repetition penalty

### ISSUE THREAD

**Issue by aviralchawla** [mlx-chat/mlx-chat-app#30]
] - event compiled client and server successfully in 925 ms (306 modules)
[0] - wait compiling...
[0] - event compiled client and server successfully in 151 ms (306 modules)
[1] 2024-03-06 10:51:50.280 Electron[98406:10012597] NSWindow does not support nonactivating panel styleMask 0x80
[1] 2024-03-06 10:51:50.281 Electron[98406:10012597] NSWindow does not support nonactivating panel styleMask 0x80
[0] - wait compiling /page (client and server)...
[1] 2024-03-06 10:51:50.395 Electron[98406:10012597] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
[0] Browserslist: caniuse-lite is outdated. Please run:
[0]   npx update-browserslist-db@latest
[0]   Why you should do it regularly: https://github.com/browserslist/update-db#readme
[0] - event compiled client and server successfully in 1354 ms (689 modules)
[0] - wait compiling...
[0] - event compiled successfully in 100 ms (378 modules)
[1] APP: Starting server for model: mistralai/Mistral-7B-Instruct-v0.2 on port: 8080
[1] Server error: Traceback (most recent call last):
[1]   File "/Users/aviralchawla/miniconda/envs/llama/lib/python3.9/runpy.py", line 188, in _run_module_as_main
[1] 
[1] Server error:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
[1]   File "/Users/aviralchawla/miniconda/envs/llama/lib/python3.9/runpy.py", line 111, in _get_module_details
[1] 
[1] Server error:     __import__(pkg_name)
[1]   File "/Users/aviralchawla/Library/dev/mlx-chat-app/server/__init__.py", line 1, in <module>
[1] 
[1] Server error:     from .utils import generate, load, convert
[1]   File "/Users/aviralchawla/Library/dev/mlx-chat-app/server/utils.py", line 165
[1]     f"repetition_penalty must be a non-negative float, got {
[1]                                                             ^
[1] SyntaxError: EOL while scanning string literal

**Comment by ParkerSm1th** [comment]
Hi there! I'll take a look at this and will get back to you tonight.

**Comment by aviralchawla** [comment]
Hi Parker, thanks for a prompt response. I fixed the problem. Turns out there are some formatting errors with 3.9, but when I changed my environment to 3.12, it fixed itself!
